### ISSUE TITLE
Bug when using exclude tree and scanning folder without read permission

### ISSUE THREAD

**Issue by tompatompa75** [paolobenve/myphotoshare#49]
When you exclude or come upon a folder without read permission, None is returned for mtime. This causes an error when comparing mtime. See error below and suggested patch. I guess it can be fixed in several ways...

Great work Paulo, I really appreciate your work and the improvements you are introducing!

```
thomas@zombie:/mnt/media/various/photoshare/ps/myphotoshare/scanner$ ./main.py ../../myphotoshare.conf > /tmp/ps.log
Traceback (most recent call last):
  File "./main.py", line 258, in <module>
    main()
  File "./main.py", line 250, in main
    TreeWalker()                                                                                                                                           File "/mnt/media/various/photoshare/ps/myphotoshare/scanner/TreeWalker.py", line 50, in __init__
    [folders_album, num, max_file_date] = self.walk(Options.config['album_path'], album_cache_base, origin_album)
  File "/mnt/media/various/photoshare/ps/myphotoshare/scanner/TreeWalker.py", line 318, in walk
    max_file_date = max(max_file_date, sub_max_file_date)
TypeError: can't compare datetime.datetime to NoneType
```

```
thomas@zombie:/mnt/media/various/photoshare/ps/myphotoshare/scanner$ git diff
diff --git a/scanner/TreeWalker.py b/scanner/TreeWalker.py
index 8eb5cb2..0c28d33 100644
--- a/scanner/TreeWalker.py
+++ b/scanner/TreeWalker.py
@@ -189,14 +189,14 @@ class TreeWalker:
                if not os.access(absolute_path, os.R_OK | os.X_OK):
                        message("access denied to directory", os.path.basename(absolute_path), 1)
                        back_level()
-                       return [None, 0, None]
+                       return [None, 0, datetime(1900,1,1)]
                listdir = os.listdir(absolute_path)
                if Options.config['exclude_tree_marker'] in listdir:
                        next_level()
                        message("excluded with subfolders by marker file", Options.config['exclude_tree_marker'], 4)
                        back_level()
                        back_level()
-                       return [None, 0, None]
+                       return [None, 0, datetime(1900,1,1)]
                skip_files = False
                if Options.config['exclude_files_marker'] in listdir:
                        next_level()
thomas@zombie:/mnt/media/various/photoshare/ps/myphotoshare/scanner$
```

**Comment by paolobenve** [comment]
closed in another way, thank you very much!
